config/routes.rb
require 'resque/server'

Spylight::Application.routes.draw do

  mount Resque::Server.new, at: "/resque"

  get "errors/show"
  ActiveAdmin.routes(self)

  apipie

  resources :users

  resources :brands

  resources :product_categories

  resources :colors

  resources :stores

  resources :sources

  resources :product_images

  resources :character_images

  resources :characters

  resources :scene_appearances

  resources :scenes

  resources :outfits

  resources :categories

  resources :episode_links

  resources :movies

  resources :shows

  resources :results

  #nested routes for products
  concern :has_products do
    resources :products
  end

  resources :shows, concerns: :has_products do
    # look for way to override what we call the param for show_id, it should be show_slug
    resources :characters, concerns: :has_products
    resources :episodes, concerns: :has_products do
      resources :scenes, concerns: :has_products
    end
  end

  resources :products
  # login / logout
  match '/auth/:service/callback' => 'sessions#create', via: [:get, :post]
  match '/auth/failure' => 'services#failure', via: [:get, :post]

  get "/logout" => "sessions#destroy", as: :destroy_session
  get "/login" => "sessions#new", as: :new_session
  resources :sessions

  resource :feedback, only: [:new, :create]

  get 'home/network_menu' => 'home#network_menu'
  get 'home/character_menu' => 'home#character_menu'
  get 'home/mailchimp' => 'home#mailchimp'
  get 'home/requestaccess' => 'home#requestaccess'
  get 'episodes/seasons' => 'episodes#seasons'

  resources :home
  resources :episodes

  root 'home#index'

  match '/episodes' => 'episodes#index', via: [:get, :post]

  match '/search' => 'search#index', via: [:get, :post]

  match '/about' => 'home#about', via: [:get, :post]

  match '/contact' => 'home#contact', via: [:get, :post]


  #api resources
  #to use an api subdomain substitute this line in
  # namespace :api, :path => "", :constraints => {:subdomain => "api"}, defaults: {format: 'json'} do
  #should probably clean this up
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :shows, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
        resources :outfits, only: [:index, :show]
        resources :characters, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
          resources :outfits, only: [:index, :show]
        end
        resources :episodes, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
          resources :scenes, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
            resources :outfits, only: [:index, :show]
          end
          resources :outfits, only: [:index, :show]
        end
      end
      resources :movies, only: [:index, :show], concerns: :has_products do
        resources :scenes, only: [:index, :show], concerns: :has_products do
          resources :outfits, only: [:index, :show]
        end
        resources :outfits, only: [:index, :show]
        resources :characters, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
          resources :outfits, only: [:index, :show]
        end
      end

      resources :products, only: [:index, :show, :create, :update, :destroy]
      resources :outfits, only: [:index, :show]

      #May not be necessary to have these outside of the show scoping, but im currently adding them to allow for quick cache updates on all models
      resources :episodes, only: [:index, :show, :create, :update, :destroy]
      resources :characters, only: [:index, :show, :create, :update, :destroy]

    
      resources :users, only: [:index, :show, :create, :update, :destroy] do
        collection do
          post 'authenticate'
          post 'authenticate_or_create_with_omniauth'
        end
      end
      resources :search, only: [:index]
      resources :feedback, only: [:create]
      resources :stars, only: [:create, :destroy]
      resources :product_categories, only: [:index, :show]
    end
  end

  # Define routes for error codes
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end


end

app/models/outfit.rb
# == Schema Information
#
# Table name: outfits
#
#  id           :integer          not null, primary key
#  start_time   :integer
#  end_time     :integer
#  created_at   :datetime
#  updated_at   :datetime
#  character_id :integer
#  change       :string(255)
#  verified     :boolean
#  approved     :boolean          default(FALSE)
#  deleted_at   :datetime
#  flag         :boolean
#  creator_id   :integer
#  slug         :string(255)
#  featured     :boolean          default(FALSE)
#

class Outfit < ActiveRecord::Base
  acts_as_paranoid
  include Reviewable

  scope :finder, lambda { |q| where("slug ILIKE :q", q: "%#{q}%") }
  scope :finder_with_offset, lambda { |q, page, page_limit| where("slug ILIKE :q", q: "%#{q}%").offset((page - 1) * page_limit).limit(page_limit) }
  scope :contains_exact_match, -> { where(contains_exact_match: true) }
  def as_json(options={})
    { id: self.id, text: self.slug }
  end

  def update_contains_exact_match
    update_column(:contains_exact_match, outfit_products.exact_match.any?)
  end

  has_many :active_admin_comments, as: :resource, dependent: :destroy
  # Search related
  # where did the search related stuff go?
  belongs_to  :character
  has_one     :show, through: :character
  has_one     :movie, through: :character
  has_many    :outfit_products
  has_many    :products, through: :outfit_products
  has_many    :outfit_images, dependent: :destroy

  has_many :stars, as: :starable
  has_many :comments, as: :commentable

  has_and_belongs_to_many :scenes
  has_many :episodes, through: :scenes

  accepts_nested_attributes_for :outfit_images, allow_destroy: true
  accepts_nested_attributes_for :outfit_products, allow_destroy: true

  after_save :update_verification
  after_save :update_slug
  after_save :update_contains_exact_match

  validate :character_scene_source_consistency
  
  def character_scene_source_consistency
    if movie
      scenes.each do |s|
        if s.movie != movie
          errors.add(:outfit,"outfits cannot belong to a scene of a show/movie which doesn't contain their character")
        end
      end
    elsif show
      scenes.each do |s|
        if s.show != show
          errors.add(:outfit,"outfits cannot belong to a scene of a show/movie which doesn't contain their character")
        end
      end
    end
    return true
  end

  def update_slug
    update_column(:slug, ["outfit", id].join("-"))
  end


  def admin_permalink
    admin_post_path(self)
  end

  def active_products
    products.active
  end

  def missing_verifications
    conditions = {"Missing active products" => active_products.any?, "Missing episode(s)" => episodes.any?, "Missing character" => character.present?, "Missing outfit image" => outfit_images.present? }

    missing_conditions =[]
    
    conditions.each do |key, value|
      missing_conditions << key unless value
    end

    missing_conditions = missing_conditions.any? ? missing_conditions : ["All verification conditions met"]
  end

  def update_verification
    if active_products.any? && character.present? && outfit_images.any? && (episodes.any? || movie.present?)
      update_column(:verified, true)
    else
      update_column(:verified, false)
    end
    if episodes.any?
      episodes.map(&:update_verification)
    end
    if character.present?
      character.update_verification
    end
    if movie.present?
      movie.update_verification
    end
    return true
  end

  # This allows adding existing products to an outfit via formtastic
  attr_reader :existing_products_exact
  def existing_products_exact=(product_ids)
    ids = product_ids.select{|p| !p.blank?}
    unless ids.blank?
      ids.each do |id|
        self.outfit_products.build(exact_match: true, product_id: id)
      end
    end
  end
  attr_reader :existing_products_non_exact
  def existing_products_non_exact=(product_ids)
    ids = product_ids.select{|p| !p.blank?}
    unless ids.blank?
      ids.each do |id|
        self.outfit_products.build(exact_match: false, product_id: id)
      end
    end
  end

  def to_label
    "Outfit #{self.id}"
  end

  def to_s
    "Outfit #{self.id}"
  end

  def has_exact_match?
    outfit_products.detect{ |op| op.exact_match}
  end

  def filter_attributes
    attrs = []
    attrs << character.gender rescue "male"
    attrs << character.name
    attrs += episodes.map(&:id)
    attrs.flatten.to_json
  end

  #image methods for easy api call
  def mobile_thumb_image_url
    self.outfit_images.any? ? self.outfit_images.first.avatar.url(:mobile_thumb) : nil
  end

  def mobile_full_image_url
    self.outfit_images.any? ? self.outfit_images.first.avatar.url(:mobile_full) : nil
  end

  def recent_airdate
    ep = episodes.select{|e| e.airdate != nil}.max_by { |e| e.airdate}
    ep.airdate rescue 30.years.ago #if the outfit has no episodes, make it appear last (really just for incomplete data)
  end


end

app/controllers/api/v1/outfits_controller.rb
class API::V1::OutfitsController < ApplicationController
  protect_from_forgery with: :null_session
  respond_to :xml, :json
  before_action :set_outfit, only: [:show, :update, :destroy]
  # before_action :default_serializer_options

  resource_description do
    short "Outfits seen on supported shows"
    description ""
    formats ['json']
  end

  # GET /shows
  # GET /shows.json
  api :GET, "/v1/outfits", "Lists all outfits"
  api :GET, "v1/shows/:show_slug/outifts", "Lists all outfits for a given show"
  api :GET, "v1/movies/:movie_slug/outifts", "Lists all outfits for a given movie"
  api :GET, "/v1/shows/:show_slug/characters/:character_slug/outfits", "Lists all outfits for a given character"
  api :GET, "/v1/movies/:movie_slug/characters/:character_slug/outfits", "Lists all outfits for a given character"
  api :GET, "/v1/shows/:show_slug/episodes/:episode_slug/outfits", "Lists all outfits for a given episode"
  api :GET, "/v1/shows/:show_slug/episodes/:episode_slug/scenes/:scene_id/outfits", "Lists all outfits for a given scene"
  api :GET, "/v1/movies/:movie_slug/scenes/:scene_id/outfits", "Lists all outfits for a given scene"
  description "Returns outfits, each of which contains a number of products."
  param :cache_update, Integer, desc: "takes an integer value and returns all outfits with an greater than that value. Used for finding all new outfits since last cache update. Note: If you enter a value for cache update all other params are ignored."
  param :active, [true, false], desc: "boolean marker that when set to true only returns active objects"
  param :per_page, Integer, desc: "if given it will paginate the results of the query"
  param :page, Integer, desc: "if pagination is enabled, page will specify which range of data will be returned"
  param :no_embed, [true, false], desc: "if set to true, products will not be embeded in the JSON response. Defaults to false."
  def index
    if params[:cache_update]
      @outfits = Outfit.where("id > ?", params[:cache_update])
    elsif params[:show_id]
      @show = Show.find_by_slug(params[:show_id])
      if params[:character_id]
        @character = @show.characters.find_by_slug(params[:character_id])
        @outfits = @character.outfits
      elsif params[:episode_id]
        @episode = @show.episodes.find_by_slug(params[:episode_id])
        if params[:scene_id]
          @scene = @episode.scenes.find(params[:scene_id])
          @outfits = @scene.outfits
        else
          @outfits = @episode.outfits
        end
      else
        @outfits = @show.characters.includes(:outfits).map { |character| character.outfits}.uniq.flatten
      end
    elsif params[:movie_id]
      @movie = Movie.find_by_slug(params[:movie_id])
      if params[:character_id]
        @character = @movie.characters.find_by_slug(params[:character_id])
        @outfits = @character.outfits
      elsif params[:scene_id]
        @scene = @movie.scenes.find(params[:scene_id])
        @outfits = @scene.outfits
      else
        @outfits = @movie.characters.includes(:outfits).map { |character| character.outfits}.uniq.flatten
      end
    else
      @outfits = Outfit.all
    end
    if params[:active]
      @outfits.keep_if{|o| (o.verified && o.approved)}
    end
    if params[:per_page] && params[:page]
      per_page = params[:per_page].to_i
      page = params[:page].to_i
      start_index = (page - 1) * per_page
      end_index = (page * per_page) - 1
      respond_with @outfits.order('id asc')[start_index..end_index]
    else
      respond_with @outfits.sort_by{|o| o.recent_airdate}.reverse
    end
  end

  # GET /shows/1
  # GET /shows/1.json
  api :GET, "/v1/outfits/:id", "Display the details of a given outfit"
  api :GET, "/v1/shows/:show_slug/outfits/:id", "Display the details of a given outfit"
  api :GET, "/v1/shows/:show_slug/characters/:character_slug/outfits/:id", "Display the details of a given outfit"
  api :GET, "/v1/shows/:show_slug/episodes/:episode_slug/outfits/:id", "Display the details of a given outfit"
  api :GET, "/v1/shows/:show_slug/episodes/:episode_slug/scenes/:scene_id/outfits/:id", "Display the details of a given outfit"
  description "Returns an outfit that contains an array of products"
  def show
    respond_with @outfit
  end

  # # POST /shows
  # # POST /shows.json
  # api :POST, "/v1/shows/", "Create a show"
  # description "Used to create a show. Will return the JSON representation of the created show."
  # def create
  # end

  # # PATCH/PUT /shows/1
  # # PATCH/PUT /shows/1.json
  # api :PATCH, "/v1/shows/:slug", "Update an existing show."
  # description "Used to update an existing show. Will return a 204 response"
  # def update
  # end

  # # DELETE /shows/1
  # # DELETE /shows/1.json
  # api :DELETE, "/v1/shows/:slug", "Delete an existing show."
  # description "Used to delete an existing show. Will return a 204 response"
  # def destroy
  #   respond_with @show.destroy
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outfit
      @outfit = Outfit.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outfit_params
      params.require(:outfit).permit(:id)
    end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController

	def show
    @outfit = Outfit.find_by(id: params[:id])
    @character = @outfit.character
    
    # the following IF statements are if the outfit belongs to TV:
    @show = Show.find_by(id: params[:show_id]) if :show_id
    @movie = Movie.find_by(id: params[:movie_id]) if :movie_id
    @episode = @outfit.episodes.first if @outfit.episodes.any?
    
    if @episode
      @episodenumber = @episode.episode_number
      @season = @outfit.episodes.first.season
    end

    respond_to do |format|
      format.js
      format.html
    end
  end

  def index
    @json_outfits = Outfit.order('slug').finder(params[:q]).page(params[:page]).per(params[:per])
      respond_to do |format|
        format.json { render json: @json_outfits }
      end
  end


end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/views/outfits/_outfit.html.haml
%li{style: "display: inline-block"}
  = link_to outfit_path(:format => :js, :id => outfit.id, :show_id => @show.id), :remote => true do
    .outfit-details{style: "display: none"}
      .filter_attributes= outfit.filter_attributes
    .outfit-image-box
      = image_tag(outfit.outfit_images.first.avatar.url(:index_size))
      .character= outfit.character.name
      .type outfit

app/views/outfits/_outfit_for_movie.html.haml
%li{style: "display: inline-block"}
  = link_to outfit_path(:format => :js, :movie_id => @movie.id, :id => outfit.id), :remote => true do
    .outfit-image-box
      = image_tag(outfit.outfit_images.first.avatar.url(:index_size))
      .character= outfit.character.name
      .type outfit
      .outfit-details

app/views/outfits/_outfitquickview.html.haml
.close.exit
  Close
- if @movie
  #product_details
    %span= link_to "#{@movie.name}", movie_path(2)
- else
  #product_details 
    %span= link_to "#{@outfit.character.name}", show_character_path(id: @outfit.character.slug, show_id: @outfit.show.slug)
    %span= link_to "- #{@outfit.show.name}", show_episodes_path(:show_id => @outfit.show.slug)
    %span= link_to "- Season #{@season} - Episode #{@episodenumber}", show_episode_path(id: @episode.slug, show_id: @outfit.show.slug)
- if outfit.products.verified.length > 4
  .character-wearing-outfit{style: "height: 400px"}
    = image_tag(outfit.outfit_images.first.avatar.url(:medium),:style => "height:100%; width: auto")
  - outfit.products.active.each do |product|
    - if @show
      = link_to show_product_path(:format => :js, :show_id => @show.id, :id => product.id), :remote => true do
        .outfit-products.exit{style: "background-image: url(#{product.product_images.first.avatar.url(:square)}); background-size: cover; background-position: center center"} 
          - if product.exact_match?(outfit)
            .exact-match= image_tag("exactmatch.png")
          .product-description 
            - if product.brand.name == product.product_sources.first.store.name
              #{product.brand.name}
              %br
              #{product.price}
            - else
              #{product.brand.name} from #{product.product_sources.first.store.name}
              %br
              #{product.price}
    - elsif @movie
      = link_to show_product_path(:format => :js, :show_id => 16, :id => product.id), :remote => true do
        .outfit-products.exit{style: "background-image: url(#{product.product_images.first.avatar.url(:square)}); background-size: cover; background-position: center center"} 
          - unless product.any_stock
            .out-of-stock
              =image_tag("outofstock.png")
          - if product.exact_match?(outfit)
            .exact-match= image_tag("exactmatch.png")
          .product-description 
            - if product.brand.name == product.product_sources.first.store.name
              #{product.brand.name}
              %br
              #{product.product_sources.first.price.format}
            - else
              #{product.brand.name} from #{product.product_sources.first.store.name}
              %br
              #{product.product_sources.first.price.format}
- else
  .character-wearing-outfit{style:"display: inline-block; float: none"}
    = image_tag(outfit.outfit_images.first.avatar.url(:js_popup))
  - outfit.products.active.each do |product|
    - if @movie
      = link_to show_product_path(:format => :js, :show_id => 16, :id => product.id), :remote => true do
        .outfit-products.exit{style: "background-image: url(#{product.product_images.first.avatar.url(:square)}); background-size: cover; background-position: center center"} 
          - if product.exact_match?(outfit)
            .exact-match= image_tag("exactmatch.png")
          .product-description 
            - if product.brand.name == product.product_sources.first.store.name
              #{product.brand.name}
              %br
              #{product.product_sources.first.price.format}
            - else
              #{product.brand.name} from #{product.product_sources.first.store.name}
              %br
              #{product.product_sources.first.price.format}
    - elsif @show
      = link_to show_product_path(:format => :js, :show_id => @show.id, :id => product.id), :remote => true do
        .outfit-products.exit{style: "background-image: url(#{product.product_images.first.avatar.url(:square)}); background-size: cover; background-position: center center"} 
          - if product.exact_match?(outfit)
            .exact-match= image_tag("exactmatch.png")
          .product-description 
            - if product.brand.name == product.product_sources.first.store.name
              #{product.brand.name}
              %br
              #{product.product_sources.first.price.format}
            - else
              #{product.brand.name} from #{product.product_sources.first.store.name}
              %br
              #{product.product_sources.first.price.format}

app/views/outfits/show.js.erb
function lightboxProduct() {
  $('#outfit_quick_overview').lightbox_me({
    centered: true,
    zIndex: 100000,
    closeSelector: ".exit",
  });
}

$('#outfit_quick_overview').change(lightboxProduct());

$('#outfit_quick_overview').html('<%= escape_javascript("#{render :partial => 'outfitquickview', locals: {outfit: @outfit, show: @show}}").html_safe %>');