config/routes.rb
require 'resque/server'

Spylight::Application.routes.draw do

  mount Resque::Server.new, at: "/resque"

  get "errors/show"
  ActiveAdmin.routes(self)

  apipie

  resources :users

  resources :brands

  resources :product_categories

  resources :colors

  resources :stores

  resources :sources

  resources :product_images

  resources :character_images

  resources :characters

  resources :scene_appearances

  resources :scenes

  resources :outfits

  resources :categories

  resources :episode_links

  resources :movies

  resources :shows

  resources :results

  #nested routes for products
  concern :has_products do
    resources :products
  end

  resources :shows, concerns: :has_products do
    # look for way to override what we call the param for show_id, it should be show_slug
    resources :characters, concerns: :has_products
    resources :episodes, concerns: :has_products do
      resources :scenes, concerns: :has_products
    end
  end

  resources :products
  # login / logout
  match '/auth/:service/callback' => 'sessions#create', via: [:get, :post]
  match '/auth/failure' => 'services#failure', via: [:get, :post]

  get "/logout" => "sessions#destroy", as: :destroy_session
  get "/login" => "sessions#new", as: :new_session
  resources :sessions

  resource :feedback, only: [:new, :create]

  get 'home/network_menu' => 'home#network_menu'
  get 'home/character_menu' => 'home#character_menu'
  get 'home/mailchimp' => 'home#mailchimp'
  get 'home/requestaccess' => 'home#requestaccess'
  get 'episodes/seasons' => 'episodes#seasons'

  resources :home
  resources :episodes

  root 'home#index'

  match '/episodes' => 'episodes#index', via: [:get, :post]

  match '/search' => 'search#index', via: [:get, :post]

  match '/about' => 'home#about', via: [:get, :post]

  match '/contact' => 'home#contact', via: [:get, :post]


  #api resources
  #to use an api subdomain substitute this line in
  # namespace :api, :path => "", :constraints => {:subdomain => "api"}, defaults: {format: 'json'} do
  #should probably clean this up
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :shows, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
        resources :outfits, only: [:index, :show]
        resources :characters, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
          resources :outfits, only: [:index, :show]
        end
        resources :episodes, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
          resources :scenes, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
            resources :outfits, only: [:index, :show]
          end
          resources :outfits, only: [:index, :show]
        end
      end
      resources :movies, only: [:index, :show], concerns: :has_products do
        resources :scenes, only: [:index, :show], concerns: :has_products do
          resources :outfits, only: [:index, :show]
        end
        resources :outfits, only: [:index, :show]
        resources :characters, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
          resources :outfits, only: [:index, :show]
        end
      end

      resources :products, only: [:index, :show, :create, :update, :destroy]
      resources :outfits, only: [:index, :show]

      #May not be necessary to have these outside of the show scoping, but im currently adding them to allow for quick cache updates on all models
      resources :episodes, only: [:index, :show, :create, :update, :destroy]
      resources :characters, only: [:index, :show, :create, :update, :destroy]

    
      resources :users, only: [:index, :show, :create, :update, :destroy] do
        collection do
          post 'authenticate'
          post 'authenticate_or_create_with_omniauth'
        end
      end
      resources :search, only: [:index]
      resources :feedback, only: [:create]
      resources :stars, only: [:create, :destroy]
      resources :product_categories, only: [:index, :show]
    end
  end

  # Define routes for error codes
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end


end

app/controllers/api/v1/episodes_controller.rb
class API::V1::EpisodesController < ApplicationController
  protect_from_forgery with: :null_session
  respond_to :xml, :json
  before_action :set_episode, only: [:show, :update, :destroy]
  before_action :set_show, only: [:index, :create]
  # before_action :default_serializer_options

  resource_description do
    short "Episodes grouped by show"
    formats ['json']
    description "The slugs used to identify episodes are of the following format:
    The slug of the associated show, hyphen, the word season, value of the season variable, hyphen, the word episode,  value of the episode_number variable. e.g.,
    new-girl-season1-episode1"
  end

  def_param_group :episode_params do 
    param :episode, Hash, action_aware: true do
      param :name, String, desc: "Episode's name", required: true
      param :season, Fixnum, desc: "Season number", required: true
      param :episode_number, Fixnum, desc: "Which episode of a given season it is", required: true
      #param :airdate, DateTime, desc: "Original Airdate of the episode"
    end
  end
  
  api :GET, "/v1/shows/:show_slug/episodes", "Lists all episodes for a given show"
  description "Returns an Array of all episodes of the selected show. Each episode in the array contains nested objects relevant to them. E.g., each episode will contain an array of scenes and an array of episode links (links to video streams of the episode)."
  param :cache_update, Integer, desc: "takes an integer value and returns all episodes with an greater than that value. Used for finding all new episodes since last cache update. Note: If you enter a value for cache update all other params are ignored."
  param :active, [true, false], desc: "boolean marker that when set to true only returns active objects"
  def index
    if params[:cache_update]
      @episodes = Episode.where("id > ?", params[:cache_update])
    elsif @show
      @episodes = @show.episodes
    else
      @episodes = Episode.all
    end
    if params[:active]
      @episodes.keep_if{|e| (e.verified && e.approved)}
    end
    respond_with @episodes.where("airdate IS NOT NULL").order('airdate DESC')
  end

  api :GET, "/v1/shows/:show_slug/episodes/:slug", "Fetches details of a single episode"
  def show
    respond_with @episode
  end

  # api :POST, "/v1/shows/:show_slug/episodes", "Create a new episode"
  # description "Create an episode for a given show. Will return a JSON representation of the show for which you just created an episode" #This should really just return the episode, but that creates an error for some reason
  # param_group :episode_params
  # def create
  #   @show.episodes.build(episode_params)
  #   @show.save
  #   respond_with @show 
  # end

  # api :PATCH, "/v1/shows/:show_slug/episodes/:slug", "Update an existing episode"
  # description "Used to update an existing episode within a given show. Will return a 204 response."
  # param_group :episode_params
  # def update
  #   respond_with @episode.update_attributes(episode_params)
  # end

  # api :DELETE, "/v1/shows/:show_slug/episodes/:slug", "Delete an existing episode"
  # description "Used to delete an existing episode within a given show. Will return a 204 response."
  # def destroy
  #   respond_with @episode.destroy
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      set_show
      @episode = @show.episodes.find_by_slug(params[:id])
    end

    def set_show
      @show = Show.find_by_slug(params[:show_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:name, :season, :episode_number)
    end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show]
  before_action :set_main_menu
  before_action :categories

  # GET /episodes
  # GET /episodes.json

  PER_PAGE = 15

  def index

    @show_episodes = @show.episodes.active
    @sorted_episodes = @show_episodes.sort_by(&:airdate).reverse

    if @sorted_episodes.any?
      redirect_to show_episode_path(show_id: @show.slug, id: @sorted_episodes.first.slug)
    else
      redirect_to show_episode_path(show_id: @show.slug, id: @show.episodes.last.slug)
    end

  end

  def seasons
    @season = params[:season]
    @show = Show.find(params[:show_id])
    @episodes = @show.episodes.active.where(season: params[:season])
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show

    # If episodes page showes firstly, it should need to get all information of filter.
    if params[:product_page].blank? & params[:outfit_page].blank?
      @products = @episode.products.active.uniq
      @characters = @episode.characters.active
      @outfits = @episode.outfits.includes([:outfit_products, :episodes]).active.uniq

      @episodes = @show.episodes.active.includes(:episode_images).where(season: @episode.season).sort_by(&:airdate).reverse
      
      # choose the episode's active characters that have been assigned importances and sort by importance.
      @characters = @episode.outfits.includes(:character).active.uniq.map{|x| x.character}.uniq.select{|x| x.active?}.select{|ch, o| ch.importance}.sort_by{|ch| ch.importance}

      # The following is for the .item-preview

        # Only select characters with exact matches for that particular episode and sort them by importance
        @characters_with_exact_matches = @episode.outfits.includes({:outfit_products => [:product, {:outfit => :character}]}).active.uniq.map{|x| x.outfit_products}.flatten.uniq.select{|op| op.exact_match? && op.product && op.active? }.flatten.group_by{|op| op.outfit.character}.select{|ch, o| ch.importance}.sort_by{|ch, o| ch.importance}.take(3)
        

        # TODO: Think about what happens if there are no exact matches in an episode. 
        # ANSWER: Well, I made it so that verified episodes MUST have at least one exact match.

      # show products that are active outfit_products; make sure there are no repeats
      @products = @episode.products.includes(:brand).active.uniq

      # The episodes that available outfits appear in
      @outfitepisodes = @outfits.map(&:episodes).flatten.select(&:active?).uniq

      # Counting how many of each category there are.
      categories = @products.includes(:product_categories).map{|p| p.product_categories}.flatten.compact.map(&:name)
      count = Hash.new(0)
      categories.each{ |category| count[category] += 1 }
      @categorycount = count.to_a

      #Counting how many of each gender there are:
      genders = @products.map{|p| p.gender}
      @gendercount = genders.group_by{|g| g}.map{|gender, product| [gender, product.size]}

      #Characters: counts how many of each character there are
      characters = @products.includes(:characters).map{|p| p.characters}.flatten.compact
      @charactercount = characters.group_by(&:name).map{|character, product| [character, product.size]}
      
      @filter = params[:filter]

      @products = @products.slice(0, PER_PAGE).compact
      @outfits = @outfits.slice(0, PER_PAGE).compact

      params[:product_page] = @products.length == PER_PAGE ? 1 : -1
      params[:outfit_page] = @outfits.length == PER_PAGE ? 1 : -1

    else
      if params[:product_page].present?
        @products = @episode.products.includes(:brand).active.uniq.offset(params[:product_page].to_i * PER_PAGE).limit(PER_PAGE)
        params[:product_page] = @products.length == PER_PAGE ? params[:product_page].to_i + 1 : -1
      else
        @outfits = @episode.outfits.includes([:outfit_products, :episodes]).active.uniq.offset(params[:outfit_page].to_i * PER_PAGE).limit(PER_PAGE)
        params[:outfit_page] = @outfits.length == PER_PAGE ? params[:outfit_page].to_i + 1 : -1
      end
    end

    respond_to do |format|
      format.html
      format.js
    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find_by_slug(params[:id])
      @show = @episode.show
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:season, :episode_number, :name, :airdate, :show_id)
    end

  # def authenticate_if_exclusive
  #   if [37, 35, 32, 30, 27].include? @show.id
  #     authenticate_or_request_with_http_basic 'Staging' do |name, password|
  #       (name == 'staging_user' && password == 'spylight_confidential') || (name == "jay" && password == "levine")
  #     end
  #   end
  # end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_accordion.html.haml
%ul#accordion
  - @outfits_by_character.take(5).each_with_index do |(character, outfits), index|
    %li{class: "slide#{index}"}
      .slide_handle
        %div
          = character.name.split.first
      .slide_content
        - if outfits.any? then
          %ul{class: "outfits", id: "makeMeScrollable#{index}"}
            .scrollWrapper
              .scrollableArea
                - outfits.each do |outfit|
                  %li
                    .img-box
                      = link_to(image_tag(outfit.outfit_images.first.avatar.url(:medium), :class => "outfit"), outfit_path(:format => :js, :show_id => @show.id, :id => outfit.id), :remote => true)
                %li{style: "display:inline-block"}
                  = link_to show_character_path(id: character.slug, show_id: @show.slug) do
                    .img-box{style: "background-image: url('#{character.character_images.thumbnail.first.avatar(:medium)}'); background-size: cover; background-position: center"}
                      .overlay
                      .text See all #{character.name}
                  



:javascript

  $("ul#accordion > li").hover(function(){
      $(this).children("div#slide-top").stop().slideToggle(500);
    });

app/views/episodes/_episode_dropdown.html.haml
.selected-episode
	Select Episode
	%i.fa.fa-angle-down{style: "float:right"}
.more-episodes
	- @episodes.each do |ep|
		= link_to show_episode_path(id: ep.slug, show_id: @show.slug) do
			.episode
				.episode-img-box= image_tag(ep.episode_images.first.avatar(:medium), :id => "episode-pic")
				.episode-info
					S#{ep.season} Episode #{ep.episode_number}
					%br #{ep.name}

app/views/episodes/_episodesthumbnail.html.haml
.episode-thumbnail
	.episode-pic
		= image_tag("newgirlvirgins.jpg", :id => "episode-pic")
	.thumbnail-footer
		.episode-number Season 3, Episode 12
		.episode-title "Virgins"

app/views/episodes/seasons.js.erb
// This is what happens when a user clicks on a specific season in the season dropdown.


$('.episode-dropdown').html('<%= escape_javascript("#{render :partial => 'episodes/episode_dropdown', locals: {show: @show, episodes: @episodes}}").html_safe %>');

app/views/episodes/show.html.haml
%head
  %title= "Spylight" + " " + "#{@show.name}" + "#{@episode.name}"

.episode-page-wrap{style: "width: 100%"}  

  .center-content
    .episode-selector-menu
      .show-name
        %div= @show.name
      .season-dropdown 
        .selected-season
          Season #{@episode.season}
          %i.fa.fa-angle-down{style: "float:right"}
        .more-seasons
          - @show.seasons.each do |s|
            = link_to episodes_seasons_path(:format => :js, :season => s, :show_id => @show.id, :id => @episode.id), :remote => true do
              .season
                %div SEASON #{s}
      .episode-dropdown
        .selected-episode
          Episode #{@episode.episode_number}
          %i.fa.fa-angle-down{style: "float:right"}
        .more-episodes
          - @episodes.each do |ep|
            = link_to show_episode_path(id: ep.slug, show_id: @show.slug) do
              .episode
                .episode-img-box= image_tag(ep.episode_images.first.avatar(:medium), :id => "episode-pic")
                .episode-info
                  S#{ep.season} Episode #{ep.episode_number}
                  %br #{ep.name}

    .about-episode.noskimwords
      .semitransparent-bg-2
      - if @episode.episode_images.any?
        .episode-picture{style: "background-image: url('#{@episode.episode_images.first.avatar(:cover)}')"}
        / = image_tag(@episode.episode_images.primary.first.avatar.url(:cover), :id => "episodestill")
        .overlay
      .episode-name= @episode.name
      .episode-airdate= @episode.airdate.strftime("Aired %m/%d/%Y")
    .item-preview
      .text
        In this episode: 
        %br
        - @characters_with_exact_matches.each do |char, prods|
          %span{style:"font-weight: 600"} #{char.name}
          %span wore
          - prods.take(3).each do |p|
            - if p.product.product_categories.any?
              - if p == prods.take(3).last && prods.length >= 2
                %span and
                - if p.product.product_categories.first.singular? 
                  %span a 
                  = link_to show_product_path(:format => :js, :show_id => @show.id, :id => p.product_id), :remote => true do
                    %span{style: "border-bottom: 1px solid gray; color: lightgray"} #{p.product.brand.name} #{p.product.product_categories.first.name}
                  %span .
                - else
                  = link_to show_product_path(:format => :js, :show_id => @show.id, :id => p.product_id), :remote => true do
                    %span{style: "border-bottom: 1px solid gray; color: lightgray"} #{p.product.brand.name} #{p.product.product_categories.first.name}
                  %span . 
              - elsif p == prods.take(3).last && prods.length < 2
                - if p.product.product_categories.first.singular? 
                  %span a 
                  = link_to show_product_path(:format => :js, :show_id => @show.id, :id => p.product_id), :remote => true do
                    %span{style: "border-bottom: 1px solid gray; color: lightgray"} #{p.product.brand.name} #{p.product.product_categories.first.name}
                  %span .
                - else
                  = link_to show_product_path(:format => :js, :show_id => @show.id, :id => p.product_id), :remote => true do
                    %span{style: "border-bottom: 1px solid gray; color: lightgray"} #{p.product.brand.name} #{p.product.product_categories.first.name}
                  %span . 
              - elsif p != prods.take(3).last
                - if p.product.product_categories.first.singular? 
                  %span a 
                  = link_to show_product_path(:format => :js, :show_id => @show.id, :id => p.product_id), :remote => true do
                    %span{style: "border-bottom: 1px solid gray; color: lightgray"} #{p.product.brand.name} #{p.product.product_categories.first.name}
                  %span ,
                - else
                  = link_to show_product_path(:format => :js, :show_id => @show.id, :id => p.product_id), :remote => true do
                    %span{style: "border-bottom: 1px solid gray; color: lightgray"} #{p.product.brand.name} #{p.product.product_categories.first.name}
                  %span ,
      .find-other-exact-matches Explore other exact & similar matches below!

  .filter-content#episode-filter-content
    .choose-a-character Choose A Character
    .wrapper
      - @characters.each do |c|
        %a{href: "#", class: "filter"}
          .character-thumbbox
            .character-thumbbox-img= image_tag(c.character_images.thumbnail.first.avatar.url(:thumb))
            .character-thumbbox-name= c.name
      / .character-thumbbox 
      /   .character-thumbbox-name See all
    .movie-options-wrap
      .show-outfits-or-products#show-outfits SHOW OUTFITS
      .show-outfits-or-products.nonactive#show-products SHOW PRODUCTS
    #outfits-list
      %ul.list
        - @outfits.each do |outfit|
          %li{style: "display: inline-block"}
            = link_to outfit_path(:format => :js, :id => outfit.id, :show_id => @show.id), :remote => true do
              .outfit-details{style: "display: none"}
                .filter_attributes= outfit.filter_attributes
              .outfit-image-box
                = image_tag(outfit.outfit_images.first.avatar.url(:index_size))
                .character= outfit.character.name
                .type outfit
        = render :partial => "products/product", :collection => @products

      #more-outfit-loader.display-none
        %center
          = image_tag "loadmore.gif"

      #more-product-loader.display-none
        %center
          = image_tag "loadmore.gif"

  = hidden_field_tag 'outfit_page', params[:outfit_page]
  = hidden_field_tag 'product_page', params[:product_page]

#outfit_quick_overview

/ js: outfit_prod_toggle.js

:javascript
  
  var outfit_page = 0;
  var product_page = 0;
  
  $(window).scroll(function(){
    if ( $(window).scrollTop() == $(document).height() - $(window).height()) {
      if ($('#show-products').hasClass('nonactive')) {
        if ( ($('#outfit_page').val() == '-1') || ($('#outfit_page').val() == outfit_page) ) return;
        $('#more-outfit-loader').show();
        $.ajax({
          url: "/shows/#{params[:show_id]}/episodes/#{params[:id]}?format=js&outfit_page=" + $('#outfit_page').val(),
          success: function( data ) {
          }
        });
        outfit_page = $('#outfit_page').val();
      } else {
        if ( ($('#product_page').val() == '-1') || ($('#product_page').val() == product_page) ) return;
        $('#more-product-loader').show();
        $.ajax({
          url: "/shows/#{params[:show_id]}/episodes/#{params[:id]}?format=js&product_page=" + $('#product_page').val(),
          success: function( data ) {
          }
        });
        product_page = $('#product_page').val();
      }
    }
  });

  $(function() {
    $('#episode-carousel').jcarousel();

    $('.episode-prev').jcarouselControl({
        target: '-=4'
    });

    $('.episode-next').jcarouselControl({
        target: '+=4'
    });

  });

    $(document).ready(function() {
    
      var newFunction = function(){   
        $('.scrollableArea').each(function() {
          var outfits = $(this).children('li').size();
          var width = outfits*160;
          $(this).css("width", width);
        });
      };

      $("#makeMeScrollable0").smoothDivScroll({
        autoScrollingMode: "",
        hotSpotScrollingInterval: 45,
        setupComplete: newFunction,
      });

      $("#makeMeScrollable1").smoothDivScroll({
        autoScrollingMode: "",
        hotSpotScrollingInterval: 5,
        setupComplete: newFunction,
      });

       $("#makeMeScrollable2").smoothDivScroll({
        autoScrollingMode: "",
        hotSpotScrollingInterval: 5,
        setupComplete: newFunction,
      });

       $("#makeMeScrollable3").smoothDivScroll({
        autoScrollingMode: "",
        hotSpotScrollingInterval: 5,
        setupComplete: newFunction,
      });

       $("#makeMeScrollable4").smoothDivScroll({
        autoScrollingMode: "",
        hotSpotScrollingInterval: 5,
        setupComplete: newFunction,
      });

    });

    $('#accordion').accordionza({
      autoPlay: false,
      captionDelay: 1000,
      captionEasing: 'easeOutBounce',
      captionHeight: 40,
      captionHeightClosed: 10,
      navKey: true,
      pauseOnHover: true,
      slideSpeed: 700,
      slideDelay: 6000,
    });


    $("ul#show-navigation-top > li").hover(function(){
      $(this).children("div#slide-top").stop().slideToggle(500);
    });

app/views/episodes/show.js.erb
// To show products
<% unless @products.blank? %>
	$('#more-product-loader').hide();
	$('#product_page').val( "<%= params[:product_page] %>" );

	// To remove all filters, so that all items including products and outfits can be considered.
	featureList.filter();

	<% @products.each do |product| %>
		var product = "<%= escape_javascript( render partial: 'products/product',
		 locals: {product: product}) %>";
		$('#outfits-list ul.list').append(product);
	<% end %>
		
	featureList = new List('outfits-list', options);

	if ($('.selected').length) {

	  // find that character's name
	  var character = $('.selected').find('.character-thumbbox-name').text();

	  featureList.filter(function(item) {
	    // show only outfits and items that belong to that character
	    if ((item.values().type == "product") && (item.values().character == character)) {
	      return true;
	    } else {
	      return false;
	    }
	  });
	} else {
		featureList.filter(function(item) {
	    // show only outfits and items that belong to that character
	    if (item.values().type == "product") {
	      return true;
	    } else {
	      return false;
	    }
	  });
	}
	
<% else %>
	<% if params[:product_page].present? %>
		$('#more-product-loader').hide();
		$('#product_page').val('-1');
	<% end %>
<% end %>

// To show outfits
<% unless @outfits.blank? %>
	$('#more-outfit-loader').hide();
	$('#outfit_page').val( "<%= params[:outfit_page] %>" );
	featureList.filter();

	<% @outfits.each do |outfit| %>
		var outfit = "<%= escape_javascript( render partial: 'outfits/outfit',
		 locals: {outfit: outfit}) %>";
		$('#outfits-list ul.list').append(outfit);	
	<% end %>
	
	featureList = new List('outfits-list', options);
	
	if ($('.selected').length) {

	  // find that character's name
	  var character = $('.selected').find('.character-thumbbox-name').text();

	  featureList.filter(function(item) {
	    // show only outfits and items that belong to that character
	    if ((item.values().type == "outfit") && (item.values().character == character)) {
	      return true;
	    } else {
	      return false;
	    }
	  });
	} else {
		featureList.filter(function(item) {
	    // show only outfits and items that belong to that character
	    if (item.values().type == "outfit") {
	      return true;
	    } else {
	      return false;
	    }
	  });
	}
<% else %>
	<% if params[:outfit_page].present? %>
		$('#more-outfit-loader').hide();
		$('#outfit_page').val('-1');		
	<% end %>
<% end %>