config/routes.rb
require 'resque/server'

Spylight::Application.routes.draw do

  mount Resque::Server.new, at: "/resque"

  get "errors/show"
  ActiveAdmin.routes(self)

  apipie

  resources :users

  resources :brands

  resources :product_categories

  resources :colors

  resources :stores

  resources :sources

  resources :product_images

  resources :character_images

  resources :characters

  resources :scene_appearances

  resources :scenes

  resources :outfits

  resources :categories

  resources :episode_links

  resources :movies

  resources :shows

  resources :results

  #nested routes for products
  concern :has_products do
    resources :products
  end

  resources :shows, concerns: :has_products do
    # look for way to override what we call the param for show_id, it should be show_slug
    resources :characters, concerns: :has_products
    resources :episodes, concerns: :has_products do
      resources :scenes, concerns: :has_products
    end
  end

  resources :products
  # login / logout
  match '/auth/:service/callback' => 'sessions#create', via: [:get, :post]
  match '/auth/failure' => 'services#failure', via: [:get, :post]

  get "/logout" => "sessions#destroy", as: :destroy_session
  get "/login" => "sessions#new", as: :new_session
  resources :sessions

  resource :feedback, only: [:new, :create]

  get 'home/network_menu' => 'home#network_menu'
  get 'home/character_menu' => 'home#character_menu'
  get 'home/mailchimp' => 'home#mailchimp'
  get 'home/requestaccess' => 'home#requestaccess'
  get 'episodes/seasons' => 'episodes#seasons'

  resources :home
  resources :episodes

  root 'home#index'

  match '/episodes' => 'episodes#index', via: [:get, :post]

  match '/search' => 'search#index', via: [:get, :post]

  match '/about' => 'home#about', via: [:get, :post]

  match '/contact' => 'home#contact', via: [:get, :post]


  #api resources
  #to use an api subdomain substitute this line in
  # namespace :api, :path => "", :constraints => {:subdomain => "api"}, defaults: {format: 'json'} do
  #should probably clean this up
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :shows, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
        resources :outfits, only: [:index, :show]
        resources :characters, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
          resources :outfits, only: [:index, :show]
        end
        resources :episodes, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
          resources :scenes, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
            resources :outfits, only: [:index, :show]
          end
          resources :outfits, only: [:index, :show]
        end
      end
      resources :movies, only: [:index, :show], concerns: :has_products do
        resources :scenes, only: [:index, :show], concerns: :has_products do
          resources :outfits, only: [:index, :show]
        end
        resources :outfits, only: [:index, :show]
        resources :characters, only: [:index, :show, :create, :update, :destroy], concerns: :has_products do
          resources :outfits, only: [:index, :show]
        end
      end

      resources :products, only: [:index, :show, :create, :update, :destroy]
      resources :outfits, only: [:index, :show]

      #May not be necessary to have these outside of the show scoping, but im currently adding them to allow for quick cache updates on all models
      resources :episodes, only: [:index, :show, :create, :update, :destroy]
      resources :characters, only: [:index, :show, :create, :update, :destroy]

    
      resources :users, only: [:index, :show, :create, :update, :destroy] do
        collection do
          post 'authenticate'
          post 'authenticate_or_create_with_omniauth'
        end
      end
      resources :search, only: [:index]
      resources :feedback, only: [:create]
      resources :stars, only: [:create, :destroy]
      resources :product_categories, only: [:index, :show]
    end
  end

  # Define routes for error codes
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :categories
  before_action :set_main_menu

  def index
    @outfits_featured = Outfit.includes(:show).where(featured: true).take(2)
    @characters_featured = Character.where(featured: true).take(2)
  end

  def about
  end

  def contact
  end

  def network_menu
    @network = Network.find_by(id: params[:network_id])
    @default = @network.shows.active.first.show_images.cover.first.avatar.url(:medium)
    respond_to do |format|  
      format.js
      format.html
    end
  end

  def mailchimp
    respond_to do |format|
      format.js
    end
  end

  def requestaccess
    respond_to do |format|
      format.js
    end
  end

  def character_menu
    @show = Show.find_by(id: params[:show_id])
    @characters = @show.characters.active
    respond_to do |format|
      format.js
      format.html
    end
  end

  private


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_maincarousel.html.haml
%ul.rslides.noskimwords
  %li
    .overlay
    #centertag
      = image_tag("centerspeechbubble.png", :id => "centerspeechbubble")
      #tagline
        Shop what your favorite stars are wearing.
    .inside-slide
      = render partial: "sidecarousel"
      .semitransparent-bg
    .tvshowlabel
      #name New Girl
      #time TUE 9/8c
      #network= image_tag("foxlogo.png")
  %li
    .overlay
    #centertag
      = image_tag("centerspeechbubble.png", :id => "centerspeechbubble")
      #tagline
        Shop what your favorite stars are wearing.
    .inside-slide
      .semitransparent-bg
      = render partial: "sidecarousel2"
    .tvshowlabel
      #name White Collar
      #time THUR 9/8c
      #network= image_tag("foxlogo.png")
  %li
    .overlay
    #centertag
      = image_tag("centerspeechbubble.png", :id => "centerspeechbubble")
      #tagline
        Shop what your favorite stars are wearing.
    .inside-slide
      .semitransparent-bg
      = render partial: "sidecarousel3"
    .tvshowlabel
      #name Scandal
      #time THUR 10/9c
      / #network
      /   %a{href: '/'}
      /     = image_tag("foxlogo.png")

app/views/home/about.html.haml
.about-content-wrapper
	.about-spylight About us
	.hiring 
		%div 
			%span{style: "font-weight: bold; text-transform: uppercase;"} We're Hiring!
			%br Introduce
			yourself at 
			%span{style: "font-style: italic"} 
				%a{href: "mailto:hiring@spylight.com"} hiring@spylight.com

	%br
	.promo-pic{style: "float: left"}= image_tag("EmmaBlake.png")
	.promo-pic{style: "float: right"}= image_tag("SpylightAd4.png")
	
	.about-content
		%p{style: "font-weight: bold"} What is Spylight?
		%p Spylight is a second screen technology that makes content shoppable. We provide a consumer-oriented mobile application and service that enables viewers to purchase goods and apparel they see on highly popular TV shows. 
		%br
		%p{style: "font-weight: bold"} Do you match exactly what actors are wearing?
		Yes, Spylight works with studios to identify the exact item (product and brand) that actors wear on set. For some items that cannot be exactly identified we provide similar look-alikes. We also provide cheaper alternatives to high-end products.
		%br
		%br
		%p{style: "font-weight: bold"} When do you reveal what products the characters are wearing?
		Spylight reveals the clothing from an episode as soon as the episode begins to air for the first time on television. For example, if a new episode of New Girl airs at 8pm (EST) on Tuesday, the clothes will be available at 8pm.
		%br
		%br

	.connect-with-spylight
		Connect with us:
		.social-links
			.social-link
				%a{href: "https://www.facebook.com/pages/Spylight/147130492137241?sk=timeline"}
					%i.fa.fa-facebook{style: "margin-right: 3px;"} 
					FACEBOOK
			.social-link
				%a{href: "http://www.pinterest.com/spylightmedia"} 
					%i.fa.fa-pinterest
					PINTEREST
			.social-link		
				%a{href: "http://www.twitter.com/spylight"}
					%i.fa.fa-twitter
					TWITTER
	.connect-with-spylight
		General Inquiries:
		%br
		%br
		%a{href: "mailto:support@spylight.com", style: "text-transform: none; text-decoration: underline"} support@spylight.com

	.connect-with-spylight
		Press Inquiries:
		%br
		%br
		%a{href: "mailto:press@spylight.com", style: "text-transform: none; text-decoration: underline"}
			press@spylight.com

app/views/home/character_menu.js.erb
// This is what happens when a user clicks on a show in the TV submenu

$('#character-submenu-placeholder').html('<%= escape_javascript("#{render :partial => 'layouts/characters_submenu', locals: {show: @show}}").html_safe %>');
$('#episode-submenu-placeholder').html('<%= escape_javascript("#{render :partial => 'layouts/episodes_submenu', locals: {show: @show}}").html_safe %>');

app/views/home/contact.html.haml
.about-content-wrapper
	.about-spylight How can we help you?

	.connect-with-spylight
		Connect with us:
		%span.social-links
			.social-link
				%i.fa.fa-facebook{style: "margin-right: 3px;"} 
				FACEBOOK
			.social-link
				%a{href: "http://www.pinterest.com/spylightmedia"} 
					%i.fa.fa-pinterest
					PINTEREST
			.social-link		
				%a{href: "http://www.twitter.com/spylight"}
					%i.fa.fa-twitter
					TWITTER

app/views/home/index.html.haml
= javascript_include_tag "home"

.jcarousel
  %ul
    %li
      .tagline Shop exactly what they're wearing.
      / .overlay
      .main-pic
        .show-info
          New Girl
          %br TUE 9/8c
          %span= image_tag('foxlogo.png', :class => "network")
        = image_tag('new_girl_landing_page.jpg')
        %script{:async => "", :charset => "utf-8", :src => "//cdn.thinglink.me/jse/embed.js"}
      %ul.example-items
        = link_to show_product_path(:format => :js, :show_id => "new-girl", :id => 6492), :remote => true do
          %li.example-item
            = image_tag(Product.find(6492).product_images.first.avatar.url(:square), :class => "exampleimage")
        = link_to show_product_path(:format => :js, :show_id => "new-girl", :id => 1798), :remote => true do
          %li.example-item
            = image_tag(Product.find(1798).product_images.first.avatar.url(:square), :class => "exampleimage")
        = link_to show_product_path(:format => :js, :show_id => "new-girl", :id => 6496), :remote => true do
          %li.example-item
            = image_tag(Product.find(6496).product_images.first.avatar.url(:square), :class => "exampleimage")
        = link_to show_product_path(:format => :js, :show_id => "new-girl", :id => 6506), :remote => true do
          %li.example-item.example-item-last
            = image_tag(Product.find(6506).product_images.first.avatar.url(:square), :class => "exampleimage")
    %li
      .tagline Shop exactly what they're wearing.
      .show-info
      .overlay
      .main-pic
        .show-info
          White Collar
          %br THU 9/8c
          %span= image_tag('foxlogo.png', :class => "network")
        = image_tag('whitecollarlanding.jpg')
      %ul.example-items
        = link_to show_product_path(:format => :js, :show_id => "white-collar", :id => 1021), :remote => true do
          %li.example-item
            = image_tag(Product.find(1021).product_images.first.avatar.url(:square), :class => "exampleimage")
        = link_to show_product_path(:format => :js, :show_id => "white-collar", :id => 1638), :remote => true do
          %li.example-item
            = image_tag(Product.find(271).product_images.first.avatar.url(:square), :class => "exampleimage")
        = link_to show_product_path(:format => :js, :show_id => "white-collar", :id => 271), :remote => true do
          %li.example-item
            = image_tag(Product.find(827).product_images.first.avatar.url(:square), :class => "exampleimage")
        = link_to show_product_path(:format => :js, :show_id => "white-collar", :id => 768), :remote => true do
          %li.example-item.example-item-last
            = image_tag(Product.find(768).product_images.first.avatar.url(:square), :class => "exampleimage")
    %li
      .tagline Shop exactly what they're wearing.
      .show-info
      .overlay
      .main-pic
        .show-info
          Scandal
          %br THU 10/9c
        = image_tag('scandals3ep1.jpg')
      %ul.example-items
        = link_to show_product_path(:format => :js, :show_id => "scandal", :id => 1776), :remote => true, :class=>"no-access" do
          %li.example-item
            = image_tag(Product.find(1776).product_images.first.avatar.url(:square), :class => "exampleimage")
        = link_to show_product_path(:format => :js, :show_id => "scandal", :id => 1775), :remote => true, :class=>"no-access" do
          %li.example-item
            = image_tag(Product.find(1775).product_images.first.avatar.url(:square), :class => "exampleimage")
        = link_to show_product_path(:format => :js, :show_id => "scandal", :id => 1268), :remote => true, :class=>"no-access" do
          %li.example-item
            = image_tag(Product.find(1268).product_images.first.avatar.url(:square), :class => "exampleimage")
        = link_to show_product_path(:format => :js, :show_id => "scandal", :id => 1164), :remote => true, :class=>"no-access" do
          %li.example-item.example-item-last
            = image_tag(Product.find(1164).product_images.first.avatar.url(:square), :class => "exampleimage")

  %a{:class => "jcarousel-prev", :href => "#"}
    = image_tag('leftarrow.png')
  %a{:class => "jcarousel-next", :href => "#"}
    = image_tag('rightarrow.png')

.divider

/ temporarily in place of rendering the quiz partial
.quiz
  / carousel
  .quiz-carousel
    %ul
      %li.cover
        .quiz-title 
          Ladies, which TV character is your 
          %div{style: "font-family: 'Lavanderia Regular'; font-size: 80px; text-align: center;"} style soulmate?
        .next-btn{style: "bottom: 15px; right: 15px;"}
          Take the quiz
          %i.fa.fa-long-arrow-right
      %li{style: "background-color: rgb(63, 92, 117)"}
        .quiz-question What would you wear to work?
        .choices
          .choice.choice-4= image_tag("olivia-work.jpg")
          .choice.choice-5= image_tag("rachel-work.jpg")
          .choice.choice-1= image_tag("jess-work.jpg")
          .choice.choice-2= image_tag("claire-work.jpg")
          .choice.last-choice.choice-5= image_tag("gloria-work.jpg")
        .previous-btn GO BACK
        .done NEXT
      %li{style: "background-color: goldenrod"}
        .quiz-question What would you wear to the Oscar's?
        .choices
          .choice.choice-4= image_tag("olivia-oscar.jpg")
          .choice.choice-2= image_tag("claire-oscar.jpg")
          .choice.choice-3= image_tag("gloria-oscar.jpg")
          .choice.choice-1= image_tag("jess-oscar.jpg")
          .choice.last-choice.choice-5= image_tag("rachel-oscar.jpg")
        .previous-btn GO BACK
        .done NEXT
      %li{style: "background-color: #800000"}
        .quiz-question What would you wear on a date?
        .choices
          .choice.choice-1= image_tag("jess-date.jpg")
          .choice.choice-4= image_tag("olivia-date.jpg")
          .choice.choice-5= image_tag("rachel-date.jpg")
          .choice.choice-2= image_tag("claire-date.jpg")
          .choice.last-choice.choice-3= image_tag("gloria-date.jpg")
        .previous-btn GO BACK
        .done NEXT
      %li{style: "background-color: darkgray"}
        .quiz-question What would you wear to sleep?
        .choices
          .choice.choice-4= image_tag("olivia-sleep.jpg")
          .choice.choice-1= image_tag("jess-sleep.jpg")
          .choice.choice-2= image_tag("claire-sleep.jpg")
          .choice.choice-5= image_tag("rachel-sleep.jpg")
          .choice.last-choice.choice-3= image_tag("gloria-sleep.jpg")
        .previous-btn GO BACK
        .done NEXT
      %li{style: "background-color: #cc5490"}
        .quiz-question What would you wear to a girl's night out?
        .choices
          .choice.choice-2= image_tag("claire-gno.jpg")
          .choice.choice-3= image_tag("gloria-gno.jpg")
          .choice.choice-1= image_tag("jess-gno.jpg")
          .choice.choice-5= image_tag("rachel-gno.jpg")
          .choice.last-choice.choice-4= image_tag("olivia-gno.jpg")
        .previous-btn{style: "right: 330px"} GO BACK
        .done.show-results SHOW ME MY STYLE SOULMATE
        .hidden-link#one= link_to "result", result_path(id: 1)
        .hidden-link#two= link_to "result", result_path(id: 2)
        .hidden-link#three= link_to "result", result_path(id: 3)
        .hidden-link#four= link_to "result", result_path(id: 4)
        .hidden-link#five= link_to "result", result_path(id: 5)


.divider

.featured-outfits
  - @outfits_featured.each_with_index do |outfit, index|
    .featured-outfit{ :style => index == 1 ? "margin-left: 5px;" : '' }
      = link_to outfit_path(:format => :js, :show_id => outfit.show.id, :id => outfit.id), :remote => true do
        .outfit-pic
          .outfit-description
            .name #{outfit.character.name.split.first}
            .show #{outfit.show.name}
            .episode Season #{outfit.episodes.first.season} Episode #{outfit.episodes.first.episode_number}
          .overlay
          .image-preview
            .product-details
            %img
          = image_tag outfit.outfit_images.first.avatar.url(:mobile_full)
      - outfit.outfit_products.includes({:product => :brand}).take(4).each do |p|
        = link_to show_product_path(:format => :js, :show_id => "new-girl", :id => p.product.id), :remote => true do
          .outfit-product
            = image_tag p.product.product_images.first.avatar.url(:square)
            .product-info.display-none
              - if p.product.brand.present?
                #{p.product.brand.name}
                %br #{p.product.price}
.view-all-character
  - @outfits_featured.each_with_index do |outfit, index|
    = link_to show_characters_path(show_id: outfit.character.show.slug), :class=>"no-access"  do
      .view-all{ :style => index == 0 ? "margin-right: 5px;" : '' }
        = image_tag (outfit.character.character_images.cover.first.avatar.url)
        .overlay
          .text View all #{outfit.character.name}

#outfit_quick_overview

app/views/home/mailchimp.js.erb
function lightboxProduct() {
  $('#mailchimp').lightbox_me({
    centered: true,
    zIndex: 1000000000
  });
}


$('#mailchimp').change(lightboxProduct());

$('#mailchimp').html('<%= escape_javascript("#{render :partial => 'layouts/mailchimp'}").html_safe %>');

app/views/home/network_menu.js.erb
// This changes the image in the imageplaceholder to the first show in the list of shows
var show = "<%= escape_javascript(@network.shows.active.first.show_images.cover.first.avatar.url(:medium)) %>"
$('.image-placeholder > img').attr('src', show);

// This changes the text to the name of the first show in the network
$('.image-placeholder').children('.text').html('<%= @network.shows.active.first.name %>');

// These are the events that happen when a user selects a new NETWORK (eg FOX or NETFLIX)
// It takes the FIRST ACTIVE SHOW of that NETWORK and shows the characters and the episodes
$('#submenu-placeholder').hide().html('<%= escape_javascript("#{render :partial => 'layouts/show_submenu', locals: {network: @network}}").html_safe %>').fadeIn();
$('#character-submenu-placeholder').hide().html('<%= escape_javascript("#{render :partial => 'layouts/characters_submenu', locals: {show: @network.shows.active.first}}").html_safe %>').fadeIn();
$('#episode-submenu-placeholder').html('<%= escape_javascript("#{render :partial => 'layouts/episodes_submenu', locals: {show: @network.shows.active.first}}").html_safe %>').fadeIn();



// This changes the show image & name upon hovering over a show link
  $(function() {
    $('ul.show-menu li').hoverIntent(openOptions, jQuery.noop());
    function openOptions() {
      var url = $(this).children('.show-image-url').text();
      var showname = $(this).children('a').text();
      $(this).parents('.padding').children('.image-placeholder').children('img').attr('src', url);
      $(this).parents('.padding').children('.image-placeholder').children('.text').text(showname);
    }
  });

app/views/home/requestaccess.js.erb
function lightboxProduct() {
  $('#requestaccess').lightbox_me({
    centered: true,
    zIndex: 1000000000
  });
}


$('#requestaccess').change(lightboxProduct());

$('#requestaccess').html('<%= escape_javascript("#{render :partial => 'layouts/requestaccess'}").html_safe %>');